"""Review Engine enums — Sprint-07 Wave-1."""
from enum import Enum


class ReviewType(str, Enum):
    ALLOCATION_REVIEW = "ALLOCATION_REVIEW"
    CIO_DECISION_REVIEW = "CIO_DECISION_REVIEW"
    WORKER_RECOMMENDATION_REVIEW = "WORKER_RECOMMENDATION_REVIEW"
    PORTFOLIO_OUTCOME_REVIEW = "PORTFOLIO_OUTCOME_REVIEW"
    THESIS_REVIEW = "THESIS_REVIEW"


class ReviewVerdict(str, Enum):
    OUTPERFORMED = "OUTPERFORMED"
    MET_EXPECTATIONS = "MET_EXPECTATIONS"
    UNDERPERFORMED = "UNDERPERFORMED"
    FAILED = "FAILED"
    INCONCLUSIVE = "INCONCLUSIVE"


class AttributionDimension(str, Enum):
    WORKER = "WORKER"
    ALLOCATION = "ALLOCATION"
    CIO = "CIO"
    PORTFOLIO = "PORTFOLIO"


class AttributionType(str, Enum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
