"""Attribution Engine repositories — Sprint-09."""
from karsa.attribution_engine.infrastructure.repositories.attribution_record_repository import AttributionRecordRepository
from karsa.attribution_engine.infrastructure.repositories.attribution_version_registry_repository import AttributionVersionRegistryRepository
