"""AI Agent Domain Models — TradeThesis aggregate and GovernanceDecision.

Sprint-55: Models for the Researcher Agent (thesis generation) and
Governance Agent (LLM-as-a-judge validation).
"""
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
import uuid


class ThesisSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


def _generate_thesis_urn() -> str:
    """Generate a Karsa URN for a trade thesis."""
    return f"urn:karsa:thesis:{uuid.uuid4()}"


class TimeHorizon(str, Enum):
    INTRADAY = "INTRADAY"
    SWING = "SWING"       # 1-5 days
    POSITION = "POSITION"  # 1-4 weeks
    LONG_TERM = "LONG_TERM"  # 1-6 months


class RiskFlag(str, Enum):
    HALLUCINATION = "HALLUCINATION"
    LOGICAL_INCONSISTENCY = "LOGICAL_INCONSISTENCY"
    POSITION_SIZE_EXCEEDED = "POSITION_SIZE_EXCEEDED"
    HORIZON_MISMATCH = "HORIZON_MISMATCH"
    NO_RAG_CONTEXT = "NO_RAG_CONTEXT"
    PARSE_FAILURE = "PARSE_FAILURE"


@dataclass
class ConvictionScore:
    """Value object: conviction score between 0.0 and 1.0."""
    value: float = 0.0

    def __post_init__(self):
        self.value = max(0.0, min(1.0, self.value))


@dataclass
class GovernanceDecision:
    """Value object: governance agent's validation decision."""
    approved: bool = False
    reasoning: str = ""
    risk_flags: List[RiskFlag] = field(default_factory=list)
    adjusted_position_size_pct: Optional[float] = None
    model_used: str = ""
    duration_ms: int = 0


@dataclass
class TradeThesis:
    """Aggregate: a trade thesis generated by the Researcher Agent.

    Lifecycle: generated -> under_review -> approved | rejected
    """
    thesis_id: str = field(default_factory=_generate_thesis_urn)
    ticker: str = ""
    side: ThesisSide = ThesisSide.BUY
    conviction: ConvictionScore = field(default_factory=ConvictionScore)
    time_horizon: TimeHorizon = TimeHorizon.SWING
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    position_size_pct: float = 1.0
    title: str = ""
    reasoning: str = ""
    source_market_event_id: Optional[str] = None
    source_news_event_id: Optional[str] = None
    rag_context_used: bool = False
    status: str = "generated"  # generated -> under_review -> approved | rejected
    governance_decision: Optional[GovernanceDecision] = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict[str, Any]:
        """Serialize for event payload."""
        return {
            "thesis_id": self.thesis_id,
            "ticker": self.ticker,
            "side": self.side.value,
            "conviction": self.conviction.value,
            "time_horizon": self.time_horizon.value,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "position_size_pct": self.position_size_pct,
            "title": self.title,
            "reasoning": self.reasoning,
            "source_market_event_id": self.source_market_event_id,
            "source_news_event_id": self.source_news_event_id,
            "rag_context_used": self.rag_context_used,
            "status": self.status,
            "created_at": self.created_at.isoformat(),
        }
