from enum import Enum

class WorkflowState(str, Enum):
    IDEA = "IDEA"
    DRAFT = "DRAFT"
    REVIEW = "REVIEW"
    REVISION = "REVISION"
    APPROVED = "APPROVED"
    ESCALATED = "ESCALATED"
    IMPLEMENTATION = "IMPLEMENTATION"
    RELEASE = "RELEASE"
    DONE = "DONE"
    FAILED = "FAILED"
    AWAITING_PROVIDER = "AWAITING_PROVIDER"
